argo-cd:
  ## ArgoCD configuration
  ## Ref: https://github.com/argoproj/argo-cd
  ##
  nameOverride: argocd
  fullnameOverride: ""

  # Optional CRD installation for those without Helm hooks
  installCRDs: false

  global:
    image:
      repository: argoproj/argocd
      tag: v2.0.0
      imagePullPolicy: IfNotPresent
    securityContext: {}
    #  runAsUser: 999
    #  runAsGroup: 999
    #  fsGroup: 999
    imagePullSecrets: []
    hostAliases: []
    # - ip: 10.20.30.40
    #   hostnames:
    #   - git.myhostname
  # configs:
  #   secret:
  #     # bycrypt hashed admin password
  #     argocdServerAdminPassword: ${argo-password}
  server:
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - url: git@github.com:iamcaleberic/argo.git
          sshPrivateKeySecret:
            name: secret-ssh-auth
            key: ssh-privatekey