apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Values.global.argo.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.global.spec.destination.server }}
    namespace: {{ .Values.global.argo.namespace }}
  project:  {{ .Values.global.argo.project }}
  source:
    helm:
      valueFiles:
        - values.yaml
        - values-alt.yaml
      parameters:
        - name: environment
          value: "test"
    path: argo-cd/
    repoURL: {{ .Values.global.spec.source.repoURL }}
    targetRevision: {{ .Values.global.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true