global: 
  argo: 
    namespace: argocd
    project: argocd
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: git@github.com:iamcaleberic/argo.git
      targetRevision: HEAD

nginx:
  name: nginx
  namespace: nginx
  project: nginx